export const ProductData = [
    {"id": 1, "name": "Biryani", "image": "https://hinzcooking.com/wp-content/uploads/2023/03/karachi-biryani.jpg", "price": "₹250"},
    {"id": 2, "name": "Chicken Karahi", "image": "https://fatimacooks.net/wp-content/uploads/2020/02/Chicken-Karahi.jpg", "price": "₹300"},
    {"id": 3, "name": "Nihari", "image": "https://i.ndtvimg.com/i/2017-06/nihari_650x400_81498470650.jpg", "price": "₹350"},
    {"id": 4, "name": "Haleem", "image": "https://i.ytimg.com/vi/2kMZA1W4Sn8/maxresdefault.jpg", "price": "₹275"},
    {"id": 5, "name": "Chapli Kebab", "image": "https://myfoodstory.com/wp-content/uploads/2023/09/Chapli-Kebab-8.jpg", "price": "₹200"},
    {"id": 6, "name": "Seekh Kebabs", "image": "https://c.ndtvimg.com/2020-01/a39okhfk_620_625x300_21_January_20.jpg", "price": "₹220"},
    {"id": 7, "name": "Aloo Gosht", "image": "https://fatimacooks.net/wp-content/uploads/2015/07/Aloo-Gosht-Pakistani-Meat-and-Potato-Curry.jpg", "price": "₹270"},
    {"id": 8, "name": "Samosas", "image": "https://t4.ftcdn.net/jpg/05/11/08/05/360_F_511080597_NvqjRdezlARSQHy4VpAKFvUVTEeGdlLy.jpg", "price": "₹100"},
    {"id": 9, "name": "Raita", "image": "https://upload.wikimedia.org/wikipedia/commons/9/90/Raita_with_cucumber_and_mint.jpg", "price": "₹80"},
    {"id": 10, "name": "Pakoras", "image": "https://example.com/pakoras.jpg", "price": "₹150"},
    {"id": 11, "name": "Chana Masala", "image": "https://example.com/chana-masala.jpg", "price": "₹180"},
    {"id": 12, "name": "Kofta", "image": "https://example.com/kofta.jpg", "price": "₹250"},
    {"id": 13, "name": "Dal Makhani", "image": "https://example.com/dal-makhani.jpg", "price": "₹200"},
    {"id": 14, "name": "Pulao", "image": "https://example.com/pulao.jpg", "price": "₹220"},
    {"id": 15, "name": "Rogan Josh", "image": "https://example.com/rogan-josh.jpg", "price": "₹300"},
    {"id": 16, "name": "Baingan Bharta", "image": "https://example.com/baingan-bharta.jpg", "price": "₹190"},
    {"id": 17, "name": "Chicken Korma", "image": "https://example.com/chicken-korma.jpg", "price": "₹280"},
    {"id": 18, "name": "Beef Kebabs", "image": "https://example.com/beef-kebabs.jpg", "price": "₹230"},
    {"id": 19, "name": "Daal Chawal", "image": "https://example.com/daal-chawal.jpg", "price": "₹150"},
    {"id": 20, "name": "Karhi Pakora", "image": "https://example.com/karhi-pakora.jpg", "price": "₹260"},
    {"id": 21, "name": "Qeema", "image": "https://example.com/qeema.jpg", "price": "₹240"},
    {"id": 22, "name": "Naan", "image": "https://example.com/naan.jpg", "price": "₹30"},
    {"id": 23, "name": "Paratha", "image": "https://example.com/paratha.jpg", "price": "₹50"},
    {"id": 24, "name": "Keema Naan", "image": "https://example.com/keema-naan.jpg", "price": "₹80"},
    {"id": 25, "name": "Chicken Pulao", "image": "https://example.com/chicken-pulao.jpg", "price": "₹230"},
    {"id": 26, "name": "Aloo Keema", "image": "https://example.com/aloo-keema.jpg", "price": "₹220"},
    {"id": 27, "name": "Palak Paneer", "image": "https://example.com/palak-paneer.jpg", "price": "₹250"},
    {"id": 28, "name": "Chole Bhature", "image": "https://example.com/chole-bhature.jpg", "price": "₹300"},
    {"id": 29, "name": "Chicken Tikka", "image": "https://example.com/chicken-tikka.jpg", "price": "₹250"},
    {"id": 30, "name": "Mutton Pulao", "image": "https://example.com/mutton-pulao.jpg", "price": "₹270"},
    {"id": 31, "name": "Bhindi Masala", "image": "https://example.com/bhindi-masala.jpg", "price": "₹200"},
    {"id": 32, "name": "Mutton Korma", "image": "https://example.com/mutton-korma.jpg", "price": "₹320"},
    {"id": 33, "name": "Tandoori Chicken", "image": "https://example.com/tandoori-chicken.jpg", "price": "₹300"},
    {"id": 34, "name": "Bun Kebab", "image": "https://example.com/bun-kebab.jpg", "price": "₹120"},
    {"id": 35, "name": "Chicken Shawarma", "image": "https://example.com/chicken-shawarma.jpg", "price": "₹250"},
    {"id": 36, "name": "Methi Thepla", "image": "https://example.com/methi-thepla.jpg", "price": "₹150"},
    {"id": 37, "name": "Haleem", "image": "https://example.com/haleem.jpg", "price": "₹275"},
    {"id": 38, "name": "Kheer", "image": "https://example.com/kheer.jpg", "price": "₹130"},
    {"id": 39, "name": "Jalebi", "image": "https://example.com/jalebi.jpg", "price": "₹100"},
    {"id": 40, "name": "Gulab Jamun", "image": "https://example.com/gulab-jamun.jpg", "price": "₹120"},
    {"id": 41, "name": "Chappal Kebab", "image": "https://example.com/chappal-kebab.jpg", "price": "₹220"},
    {"id": 42, "name": "Shami Kebab", "image": "https://example.com/shami-kebab.jpg", "price": "₹200"},
    {"id": 43, "name": "Paya", "image": "https://example.com/paya.jpg", "price": "₹350"},
    {"id": 44, "name": "Keema", "image": "https://example.com/keema.jpg", "price": "₹240"},
    {"id": 45, "name": "Achari Chicken", "image": "https://example.com/achari-chicken.jpg", "price": "₹270"},
    {"id": 46, "name": "Dal Tadka", "image": "https://example.com/dal-tadka.jpg", "price": "₹200"},
    {"id": 47, "name": "Kofta Curry", "image": "https://example.com/kofta-curry.jpg", "price": "₹250"},
    {"id": 48, "name": "Vegetable Pulao", "image": "https://example.com/vegetable-pulao.jpg", "price": "₹220"},
    {"id": 49, "name": "Kachori", "image": "https://example.com/kachori.jpg", "price": "₹80"},
    {"id": 50, "name": "Siri Paye", "image": "https://example.com/siri-paye.jpg", "price": "₹350"},
    {"id": 51, "name": "Karhi Pakora", "image": "https://example.com/karhi-pakora.jpg", "price": "₹260"},
    {"id": 52, "name": "Keema Paratha", "image": "https://example.com/keema-paratha.jpg", "price": "₹150"},
    {"id": 53, "name": "Tandoori Roti", "image": "https://example.com/tandoori-roti.jpg", "price": "₹40"},
    {"id": 54, "name": "Pulao", "image": "https://example.com/pulao.jpg", "price": "₹220"},
]